# Generated by Django 4.2.2 on 2023-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_alter_officer_active_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='plate_type',
            field=models.CharField(max_length=8),
        ),
    ]
