# Generated by Django 4.2.2 on 2023-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_licenseplate_plate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='plate_number',
            field=models.CharField(default='TEMP', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='plate_type',
            field=models.CharField(choices=[('Municipal', (('MVN', 'Municipal Vehicle'), ('MXN', 'Municipal Motorcycle'))), ('Passenger', (('PAN', 'Passenger Normal'),)), ('XXX', 'Unknown')], default='MVN', max_length=3),
        ),
    ]
