# Generated by Django 4.2.2 on 2023-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_licenseplate_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='badge_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
