# Generated by Django 4.2.2 on 2023-06-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_officer_badge_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='badge_number',
        ),
    ]
