# Generated by Django 4.2.2 on 2023-06-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_remove_officer_badge_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='verbal_name',
        ),
    ]
