# Generated by Django 4.2.2 on 2023-06-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_rename_name_vehicle_verbal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispatch.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='radio_id',
            field=models.CharField(max_length=4, verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='variety',
            field=models.CharField(max_length=32, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='verbal_name',
            field=models.CharField(max_length=32, verbose_name='Vehicle'),
        ),
    ]
