# Generated by Django 4.2.2 on 2023-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_alter_officer_vehicle_alter_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
