# Generated by Django 4.2.2 on 2023-06-23 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_call_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='time_generated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
