# Generated by Django 4.2.2 on 2023-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_call_time_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
